"""Generic Python tool requirements for code generation validation.

This module provides a set of composable requirements for validating Python code
generated by language models. Requirements can be used individually or bundled
via the python_code_generation_requirements() factory function.

The requirement pipeline validates code in this order:
1. PythonCodeExtraction — code blocks are present and extractable
2. PythonSyntaxValid — code parses without syntax errors
3. PythonExecutionReq — code runs without exceptions and output stays within bounds
4. ImportRestrictions — only whitelisted modules are imported (optional)

OutputSizeLimit is available as a standalone requirement for special cases where
output size validation needs to be separate from execution (e.g., validating code
with non-deterministic output or checking previously-executed code).
"""

import ast

from mellea.stdlib.tools.execution_policy import CapabilityPolicy, ExecutionTier
from mellea.stdlib.tools.interpreter import (
    ExecutionEnvironment,
    make_execution_environment,
)

from ...core import Context, MelleaLogger, Requirement, ValidationResult
from .python_reqs import PythonExecutionReq, _has_python_code_listing

logger = MelleaLogger.get_logger()


class PythonCodeExtraction(Requirement):
    """Code blocks are present and extractable from model output.

    This requirement checks whether the model's response contains Python code
    blocks that can be extracted for further validation or execution.
    """

    def __init__(self) -> None:
        """Initialize PythonCodeExtraction requirement."""
        super().__init__(
            description="Code blocks are present and extractable.",
            validation_fn=_has_python_code_listing,
            check_only=True,
        )


class PythonSyntaxValid(Requirement):
    """Python code is syntactically valid (parses without AST errors).

    Uses Python's ast.parse() to validate syntax without executing code.
    Useful for catching malformed code early in the validation pipeline.
    """

    def __init__(self) -> None:
        """Initialize PythonSyntaxValid requirement."""
        super().__init__(
            description="Python code is syntactically valid.",
            validation_fn=self._validate_syntax,
            check_only=True,
        )

    def _validate_syntax(self, ctx: Context) -> ValidationResult:
        """Validate that extracted code has valid Python syntax.

        Args:
            ctx: Context containing model output with code blocks.

        Returns:
            ValidationResult with pass/fail and extracted code or error details.
        """
        extraction_result = _has_python_code_listing(ctx)
        if not extraction_result.as_bool():
            return ValidationResult(
                result=False,
                reason=f"Could not extract code for syntax validation: {extraction_result.reason}",
            )

        code = extraction_result.reason
        if code is None:
            return ValidationResult(
                result=False,
                reason="Code extraction returned None; this should not happen.",
            )

        try:
            ast.parse(code)
            return ValidationResult(result=True, reason="Syntax is valid.")
        except SyntaxError as e:
            return ValidationResult(
                result=False, reason=f"Syntax error at line {e.lineno}: {e.msg}"
            )


class OutputSizeLimit(Requirement):
    """Captured output does not exceed size limit (in characters).

    Executes code and verifies that the captured stdout does not exceed
    the configured character limit. Useful for preventing excessive logging
    or infinite output loops.

    ⚠️ **Prefer PythonExecutionReq(max_output_chars=...)**: Starting in this version,
    output size checking is integrated into PythonExecutionReq, eliminating the
    double-execution cost. Use this class only for special cases where you need
    output size validation as a separate execution pass:

    1. Validating code with non-deterministic output (where separate execution
       passes are intentional).
    2. Re-checking output size of code executed elsewhere, without repeating
       the earlier execution.
    3. Niche cases where static tier validation is desired (though static tier
       does not execute code, so this is rarely useful).

    For typical use in python_code_generation_requirements(), the bundle now uses
    PythonExecutionReq(max_output_chars=...) internally, so this class is no
    longer added to the bundle.

    ⚠️ **Static Tier Behavior**: When execution_tier is "static" (the default),
    no code execution occurs and output size is not validated. The requirement
    returns result=True, but this does not indicate the requirement was satisfied —
    only that validation was skipped. This is intentional: static tier is the
    no-execution baseline. If you need actual output size validation, set
    execution_tier to "local", "local_unsafe", or "docker".

    Args:
        limit_chars: Maximum allowed output size in characters. Defaults to 10,000.
        execution_tier: Execution environment tier. Defaults to ``"static"``
            (no execution; output limit not enforced).
        policy: Optional CapabilityPolicy to override tier defaults.
        allowed_imports: Whitelist of importable top-level modules. None allows all.
    """

    def __init__(
        self,
        limit_chars: int = 10_000,
        execution_tier: ExecutionTier = "static",
        policy: CapabilityPolicy | None = None,
        allowed_imports: list[str] | None = None,
    ) -> None:
        """Initialize OutputSizeLimit requirement.

        Raises:
            ValueError: If limit_chars is not positive.
        """
        if limit_chars <= 0:
            raise ValueError(f"limit_chars must be positive, got {limit_chars}")

        self.limit_chars = limit_chars
        self.execution_tier = execution_tier
        self.policy = policy
        self.allowed_imports = allowed_imports
        super().__init__(
            description=f"Output does not exceed {limit_chars} characters.",
            validation_fn=self._validate_output_size,
            check_only=True,
        )

    def _validate_output_size(self, ctx: Context) -> ValidationResult:
        """Validate that executed code's output stays within size limit.

        Args:
            ctx: Context containing model output with code blocks.

        Returns:
            ValidationResult with pass/fail and output size details.
            Note: When execution_tier is "static", the requirement returns result=True
            because no code execution occurs. This does not indicate validation passed —
            only that validation was skipped. Callers should not interpret result=True
            from static tier as evidence of code quality or correctness.
        """
        if self.execution_tier == "static":
            return ValidationResult(
                result=True,
                reason="Output size not validated (static analysis tier skips execution).",
            )

        extraction_result = _has_python_code_listing(ctx)
        if not extraction_result.as_bool():
            return ValidationResult(
                result=False,
                reason="Could not extract code for output size validation.",
            )

        code = extraction_result.reason
        if code is None:
            return ValidationResult(
                result=False,
                reason="Code extraction returned None; this should not happen.",
            )

        try:
            environment = make_execution_environment(
                tier=self.execution_tier,
                policy=self.policy,
                allowed_imports=self.allowed_imports,
            )
            exec_result = environment.execute(code)
            if not exec_result.success:
                return ValidationResult(
                    result=False,
                    reason=f"Code execution failed during output size check: {exec_result.to_validationresult_reason()}",
                )

            output_size = len(exec_result.stdout or "")

            if output_size <= self.limit_chars:
                return ValidationResult(
                    result=True,
                    reason=f"Output size ({output_size} chars) within limit ({self.limit_chars}).",
                )
            else:
                return ValidationResult(
                    result=False,
                    reason=f"Output size ({output_size} chars) exceeds limit ({self.limit_chars}).",
                )
        except Exception as e:
            logger.exception("Unexpected error during output size validation")
            return ValidationResult(
                result=False, reason=f"Error checking output size: {e!s}"
            )


class ImportRestrictions(Requirement):
    """Only whitelisted modules are imported in the code.

    Uses AST analysis to find all imports (Import and ImportFrom nodes)
    and validates them against an optional allowlist. If an empty list is
    provided, all imports are blocked. If None is provided, all imports are accepted.

    ⚠️ **Not a Security Boundary**: This is a static AST-based guidance check,
    not a security control. It only detects static import statements (``import x``
    and ``from x import y``) and does NOT detect dynamic imports such as:
    - ``__import__("subprocess")``
    - ``importlib.import_module("socket")``
    - ``exec("import urllib")``
    - ``eval("import os")``

    For real isolation from untrusted code, combine this requirement with
    ``execution_tier="docker"`` and a restrictive ``CapabilityPolicy``.
    The execution environment sandbox provides the actual security boundary,
    not the import allowlist.

    Args:
        allowed_imports: List of module names that are allowed to be imported.
            If None, all imports are accepted. If an empty list, all imports are blocked.
    """

    def __init__(self, allowed_imports: list[str] | None = None) -> None:
        """Initialize ImportRestrictions requirement."""
        self.allowed_imports: list[str] | None = allowed_imports
        if allowed_imports is None:
            imports_str = "all"
        else:
            imports_str = ", ".join(allowed_imports) if allowed_imports else "none"
        description = f"Only imports from [{imports_str}] are used."

        super().__init__(
            description=description,
            validation_fn=self._validate_imports,
            check_only=True,
        )

    def _validate_imports(self, ctx: Context) -> ValidationResult:
        """Validate that imports in extracted code match allowlist.

        Args:
            ctx: Context containing model output with code blocks.

        Returns:
            ValidationResult with pass/fail and forbidden imports if any.
        """
        extraction_result = _has_python_code_listing(ctx)
        if not extraction_result.as_bool():
            return ValidationResult(
                result=False, reason="Could not extract code for import validation."
            )

        code = extraction_result.reason
        if code is None:
            return ValidationResult(
                result=False,
                reason="Code extraction returned None; this should not happen.",
            )

        if self.allowed_imports is None:
            return ValidationResult(
                result=True, reason="No import restrictions configured."
            )

        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            return ValidationResult(
                result=False,
                reason=f"Could not parse code for import analysis: {e.msg}",
            )

        forbidden_imports: list[str] = []

        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                for alias in node.names:
                    module_name = alias.name.split(".")[0]
                    if module_name not in self.allowed_imports:
                        forbidden_imports.append(module_name)

            elif isinstance(node, ast.ImportFrom):
                if node.module is None:
                    # Relative-only imports like "from . import x"
                    for alias in node.names:
                        module_name = alias.name.split(".")[0]
                        if module_name not in self.allowed_imports:
                            forbidden_imports.append(module_name)
                else:
                    module_name = node.module.split(".")[0]
                    if module_name not in self.allowed_imports:
                        forbidden_imports.append(module_name)

        if forbidden_imports:
            unique_forbidden = sorted(set(forbidden_imports))
            return ValidationResult(
                result=False,
                reason=f"Forbidden imports detected: {', '.join(unique_forbidden)}",
            )

        return ValidationResult(result=True, reason="All imports are whitelisted.")


class NoImportRestrictions(Requirement):
    """Explicit no-op requirement indicating no import checks are configured.

    This requirement always passes and documents that import restrictions are
    not being enforced. Used by python_code_generation_requirements() when allowed_imports
    is None, providing semantic clarity in the requirement bundle that import
    validation was intentionally skipped (rather than silently omitting the
    requirement from the list).
    """

    def __init__(self) -> None:
        """Initialize NoImportRestrictions requirement."""
        super().__init__(
            description="No import restrictions (all imports allowed).",
            validation_fn=lambda ctx: ValidationResult(
                result=True, reason="No import restrictions configured."
            ),
            check_only=True,
        )


def python_code_generation_requirements(
    allowed_imports: list[str] | None = None,
    output_limit_chars: int = 10_000,
    timeout_seconds: int = 5,
    use_sandbox: bool = False,
) -> list[Requirement]:
    """Bundle generic Python tool requirements with configurable parameters.

    Factory function that creates a complete set of requirements for validating
    Python code generation, from extraction through execution and output checks.

    ⚠️ **Performance Improvement**: As of this version, output size checking is
    integrated into PythonExecutionReq via the max_output_chars parameter,
    eliminating the double-execution cost that occurred when OutputSizeLimit was
    a separate requirement in the bundle. This reduces execution cost for Docker-
    isolated code and reduces the attack surface for untrusted inputs.

    Args:
        allowed_imports: Whitelist of importable top-level modules. If None, all
            imports are allowed. Default None.
        output_limit_chars: Maximum allowed characters of captured stdout.
            Default 10,000.
        timeout_seconds: Maximum execution time in seconds. Default 5.
        use_sandbox: Use llm-sandbox for Docker-isolated execution. Default False.

    Returns:
        list[Requirement]: Requirement instances in validation order (always 4):
            1. PythonCodeExtraction
            2. PythonSyntaxValid
            3. PythonExecutionReq (configured with timeout, sandbox, and output limit)
            4. ImportRestrictions or NoImportRestrictions

        The fourth requirement is ImportRestrictions if allowed_imports is provided
        (enforcing the whitelist), or NoImportRestrictions if allowed_imports is None
        (documenting that no import checks are configured).

    Raises:
        ValueError: If timeout_seconds is not positive.
        ValueError: If output_limit_chars is not positive.

    Examples:
        >>> # Unrestricted execution with defaults
        >>> reqs = python_code_generation_requirements()
        >>> len(reqs)
        4
        >>> isinstance(reqs[3], NoImportRestrictions)
        True

        >>> # Restricted to safe modules only
        >>> reqs = python_code_generation_requirements(
        ...     allowed_imports=["os", "sys", "json"],
        ...     output_limit_chars=5_000,
        ... )
        >>> len(reqs)  # always 4, fourth is ImportRestrictions
        4
        >>> isinstance(reqs[3], ImportRestrictions)
        True

        >>> # Sandbox mode for untrusted code
        >>> reqs = python_code_generation_requirements(
        ...     use_sandbox=True,
        ...     timeout_seconds=10,
        ... )
    """
    if timeout_seconds <= 0:
        raise ValueError(f"timeout_seconds must be positive, got {timeout_seconds}")
    if output_limit_chars <= 0:
        raise ValueError(
            f"output_limit_chars must be positive, got {output_limit_chars}"
        )

    execution_tier: ExecutionTier = "docker" if use_sandbox else "static"
    policy = (
        None
        if execution_tier == "static"
        else CapabilityPolicy(timeout=timeout_seconds)
    )

    reqs: list[Requirement] = [
        PythonCodeExtraction(),
        PythonSyntaxValid(),
        PythonExecutionReq(
            execution_tier=execution_tier,
            policy=policy,
            allowed_imports=allowed_imports,
            max_output_chars=output_limit_chars,
        ),
    ]

    if allowed_imports is not None:
        reqs.append(ImportRestrictions(allowed_imports=allowed_imports))
    else:
        reqs.append(NoImportRestrictions())

    return reqs
