import re
from collections.abc import Callable, Sequence
from typing import TypedDict, TypeVar, Unpack, cast, final

from mellea import MelleaSession
from mellea.backends import ModelOption
from mellea.core import MelleaLogger
from mellea.stdlib.components import Message

from .._prompt_modules import PromptModule, PromptModuleString
from ._exceptions import BackendGenerationError, TagExtractionError
from ._prompt import get_system_prompt, get_user_prompt
from ._types import SubtaskPromptConstraintsItem

MelleaLogger.get_logger().setLevel("DEBUG")

T = TypeVar("T")

RE_GEN_DATA_FORMAT = re.compile(
    r"@@@\|(.+?)\|@@@###\|(.+?)\|###[\r\n|\r|\n](.+?)@@@\|GENERATION\|@@@(.+?)@@@\|DELIMITER\|@@@",
    flags=re.IGNORECASE | re.DOTALL,
)

RE_ASSIGNED_CONS = re.compile(
    r"<assigned_constraints>(.*?)</assigned_constraints>",
    flags=re.IGNORECASE | re.DOTALL,
)

# Regex to match common list formats produced by LLMs:
# - bullet lists: -, *, •, en dash, em dash
# - numbered lists: 1.  1)
RE_LIST_ITEM = re.compile(r"^\s*(?:[-*•]|[–—]|(?:\d+)[.)])\s*(.+?)\s*$")

# Regex to remove trailing "closing sentence" often generated by LLMs
RE_TRAILING_CLOSURE = re.compile(
    r"\n*All tags are closed and my assignment is finished\.\s*$", flags=re.IGNORECASE
)


class SubtaskConstraintAssignArgs(TypedDict):
    subtasks_tags_and_prompts: Sequence[tuple[str, str, str]]
    constraint_list: Sequence[str]


@final
class _SubtaskConstraintAssign(PromptModule):
    @staticmethod
    def _is_na_value(text: str) -> bool:
        """
        Check if the entire content represents a "no constraints" signal.

        This avoids false positives such as:
        "- If missing, return N/A"

        Only returns True if the WHOLE text is equivalent to N/A.
        """
        normalized = re.sub(r"\s+", "", text).upper()
        return normalized in {"N/A", "NA"}

    @staticmethod
    def _extract_constraints(text: str) -> list[str]:
        """
        Extract constraints from list-style text.

        Supports:
        - "- item"
        - "* item"
        - "• item"
        - "1. item"
        - "1) item"
        - "en dash item"
        - "em dash item"

        Returns:
            Deduplicated list while preserving order.
        """
        constraints: list[str] = []

        for line in text.splitlines():
            stripped = line.strip()
            if not stripped:
                continue

            match = RE_LIST_ITEM.match(line)
            if match:
                value = match.group(1).strip()
                if value:
                    constraints.append(value)

        # Remove duplicates while preserving order
        return list(dict.fromkeys(constraints))

    @staticmethod
    def _default_parser(generated_str: str) -> list[SubtaskPromptConstraintsItem]:
        r"""Default parser of the `subtask_constraint_assign` module.

        _**Disclaimer**: This is a LLM-prompting module, so the results will vary depending
        on the size and capabilities of the LLM used. The results are also not guaranteed, so
        take a look at this module's Exceptions and plan for unreliable results._

        This parser processes the serialized output produced by the
        `subtask_constraint_assign.generate()` method and converts it into structured
        constraint assignments for each subtask.

        The parser is designed to be robust against minor formatting variations in LLM
        responses. In particular, it:
        - extracts content from `<assigned_constraints>` tags when present;
        - falls back to the raw generated text when the expected tags are missing;
        - supports multiple list formats commonly produced by LLMs, such as `-`, `*`,
        `•`, `1.`, and `1)`;
        - treats the entire content as "no constraints" only when the full content is
        equivalent to `N/A` or `NA`;
        - falls back to using the full text as a single constraint when non-empty content
        is present but no list-style items can be parsed.

        Args:
            generated_str (`str`): The LLM output to be parsed.
                This string contains the generation results for each subtask,
                separated by internal delimiters to enable structured parsing.

        Returns:
            list[SubtaskPromptConstraintsItem]: A `list` of
            `SubtaskPromptConstraintsItem` objects where each item contains:
            - `subtask` (`str`): the subtask title or description;
            - `tag` (`str`): the variable/tag associated with the subtask;
            - `prompt_template` (`str`): the generated prompt template for the subtask;
            - `constraints` (`list[str]`): the constraints assigned to that subtask.

            Note that the `constraints` list can be empty.

            For example:
            ```
            [
                SubtaskPromptConstraintsItem(
                    subtask=<str>,
                    tag=<str>,
                    prompt_template=<str>,
                    constraints=<list[str]>,
                ),
                ...
            ]
            ```

            You can use dot notation to access the values. For example:
            ```
            result: PromptModuleString = ...  # Result of subtask_constraint_assign.generate()

            parsed_result: list[SubtaskPromptConstraintsItem] = result.parse()

            subtask_0: str = parsed_result[0].subtask
            tag_0: str = parsed_result[0].tag
            prompt_template_0: str = parsed_result[0].prompt_template
            constraints_0: list[str] = parsed_result[0].constraints
            ```

        Raises:
            This parser does not intentionally raise `TagExtractionError` when the
            expected tags are missing. Instead, it attempts to recover by falling back
            to raw generated text. Parsing may still fail indirectly if the serialized
            generation format is malformed beyond recovery.
        """
        gen_data = re.findall(RE_GEN_DATA_FORMAT, generated_str)

        result: list[SubtaskPromptConstraintsItem] = []

        for data in gen_data:
            data = cast(tuple[str, str, str, str], data)

            # Try extracting content inside <assigned_constraints> tags
            subtask_constraint_assign_match = re.search(RE_ASSIGNED_CONS, data[3])

            if subtask_constraint_assign_match:
                subtask_constraint_assign_str = subtask_constraint_assign_match.group(
                    1
                ).strip()
            else:
                # Fallback to raw text if tags are missing
                MelleaLogger.get_logger().warning(
                    "Expected tags missing from LLM response; falling back to raw response text. "
                    "Downstream stages may receive unstructured content."
                )
                subtask_constraint_assign_str = data[3].strip()

            # Remove common trailing LLM artifacts
            subtask_constraint_assign_str = re.sub(
                RE_TRAILING_CLOSURE, "", subtask_constraint_assign_str
            ).strip()

            # Handle "no constraints" case
            if _SubtaskConstraintAssign._is_na_value(subtask_constraint_assign_str):
                subtask_constraint_assign: list[str] = []

            else:
                # Try extracting list-style constraints
                subtask_constraint_assign = (
                    _SubtaskConstraintAssign._extract_constraints(
                        subtask_constraint_assign_str
                    )
                )

                # -------- Secondary fallback --------
                # If content exists but no list items were parsed,
                # treat the whole text as a single constraint.
                if subtask_constraint_assign_str and not subtask_constraint_assign:
                    MelleaLogger.get_logger().warning(
                        "No list-style constraints detected; falling back to full text as a single constraint."
                    )
                    subtask_constraint_assign = [subtask_constraint_assign_str]

            result.append(
                SubtaskPromptConstraintsItem(
                    subtask=data[0].strip(),
                    tag=data[1].strip(),
                    prompt_template=data[2].strip(),
                    constraints=subtask_constraint_assign,
                )
            )

        return result

    def generate(  # type: ignore[override]
        # About the mypy ignore above:
        # Contrary to the "_ConstraintExtractor" implementation, this one does actually
        # break the Liskov Substitution Principle because of the required extra
        # arguments (with no default values) inside the "**kwargs". We can
        # later refactor the abstract class or even remove it completely.
        # TODO: Discussion and refactoring necessary (this works for now though).
        self,
        mellea_session: MelleaSession,
        input_str: str | None = None,
        max_new_tokens: int = 4096,
        parser: Callable[[str], T] = _default_parser,  # type: ignore[assignment]
        # About the mypy ignore statement above: https://github.com/python/mypy/issues/3737
        **kwargs: Unpack[SubtaskConstraintAssignArgs],
    ) -> PromptModuleString[T]:
        """Receives a list of subtasks (with their tags and template prompts) and a list
        of constraints written in natural language.

        Selects and assigns, to each subtask, the constraints that the LLM judges
        to be appropriate (among the provided constraint list) for that subtask.

        _**Disclaimer**: This is a LLM-prompting module, so the results will vary depending
        on the size and capabilities of the LLM used. The results are also not guaranteed, so
        take a look at this module's Exceptions and plan for unreliable results._

        Args:
            mellea_session (`MelleaSession`): A mellea session configured with a backend.
            input_str (`None`, optional): This module does not use the `input_str`
                argument. It is kept for interface compatibility.
            max_new_tokens (`int`, optional): Maximum number of tokens to generate
                for each LLM call. Try increasing this value if the model is truncating
                its answers. Defaults to `4096`.
            parser (`Callable[[str], Any]`, optional): A parsing function used by the
                returned `PromptModuleString.parse()` method.
                Defaults to `_SubtaskConstraintAssign._default_parser`.
            subtasks_tags_and_prompts (`Sequence[tuple[str, str, str]]`): A sequence of
                subtasks and their respective tags and prompt templates.

                This was designed to receive the parsed result of the
                `subtask_prompt_generator` module, but this is not required, as long as
                the provided data follows the expected format.

                Each item must be a `tuple[str, str, str]` where:
                - the first element is the subtask title or description in natural language;
                - the second element is a descriptive tag/variable name for that subtask;
                - the third element is the prompt template to be executed by an LLM.

                Example:
                ```
                subtasks_tags_and_prompts = [
                    (
                        "1. Read the document and write a summary",
                        "DOCUMENT_SUMMARY",
                        "<template_prompt>",
                    ),
                    (
                        "2. Write the 3 most important phrases as bullets",
                        "IMPORTANT_PHRASES",
                        "<template_prompt>",
                    ),
                ]
                ```
            constraint_list (`Sequence[str]`): A list of constraints written in natural language.

                This was designed to receive constraints extracted from the original user
                request so they can be distributed across the generated subtasks.

        Returns:
            PromptModuleString: A `PromptModuleString` containing the serialized LLM output.

            The `PromptModuleString` behaves like a `str`, but also provides a `parse()`
            method that applies the parsing function passed through the `parser`
            argument. By default, this is
            `_SubtaskConstraintAssign._default_parser`.

        Raises:
            BackendGenerationError: Raised when an LLM generation call fails, or when the
            backend returns `None` as the generated value.
        """
        system_prompt = get_system_prompt()

        execution_plan = [
            f"{subtask_tag_prompt[0]} - Variable: {subtask_tag_prompt[1]}"
            for subtask_tag_prompt in kwargs["subtasks_tags_and_prompts"]
        ]

        all_results_string = ""

        # TODO: Make this whole segment execute concurrently using regular threading
        for i, subtask_tag_prompt in enumerate(kwargs["subtasks_tags_and_prompts"]):
            user_prompt = get_user_prompt(
                execution_plan=execution_plan,
                constraint_list=kwargs["constraint_list"],
                subtask_title=subtask_tag_prompt[0],
                subtask_prompt=subtask_tag_prompt[2],
            )

            action = Message("user", user_prompt)

            try:
                gen_result = mellea_session.act(
                    action=action,
                    model_options={
                        ModelOption.SYSTEM_PROMPT: system_prompt,
                        ModelOption.TEMPERATURE: 0,
                        ModelOption.MAX_NEW_TOKENS: max_new_tokens,
                    },
                ).value
            except Exception as e:
                raise BackendGenerationError(f"LLM generation failed: {e}")

            if gen_result is None:
                raise BackendGenerationError(
                    "LLM generation failed: value attribute is None"
                )

            all_results_string = (
                all_results_string
                + f"@@@|{subtask_tag_prompt[0]}|@@@###|{subtask_tag_prompt[1]}|###\n"
                + subtask_tag_prompt[2].strip()
                + "@@@|GENERATION|@@@"
                + gen_result.strip()
                + "@@@|DELIMITER|@@@\n"
            )

        return PromptModuleString(all_results_string, parser)


subtask_constraint_assign = _SubtaskConstraintAssign()
