name: "Run CI"

on:
  pull_request:
    types: [opened, reopened, synchronize]
  merge_group:

permissions: {}

jobs:
  code-checks:
    permissions:
      contents: read
    uses: ./.github/workflows/quality.yml

